import Link from 'next/link'
import { ArrowRight, CalendarDays, MapPin, Sparkles } from 'lucide-react'
import { PageFrame, PageHero } from '@/components/site-shell'

const destinations = [
  { name: 'Sigiriya', type: 'Ancient wonder', image: '/images/sigiriya-dawn.png', intro: 'Climb the famous rock fortress at first light, then slow down among village paths, tanks and jungle.', best: 'Culture, history & sunrise', time: '2–3 nights' },
  { name: 'Kandy', type: 'Living culture', image: '/images/kandy-lake.png', intro: 'A soulful highland city of temple rituals, forest walks, music and the calm waters of Kandy Lake.', best: 'Heritage & local life', time: '2 nights' },
  { name: 'Ella', type: 'Highland escape', image: '/images/ella-mist.png', intro: 'Wake to misty peaks, tea gardens and winding train tracks before exploring waterfalls and village trails.', best: 'Mountains & soft adventure', time: '2–3 nights' },
  { name: 'Galle Fort', type: 'Coastal heritage', image: '/images/galle-fort-dusk.png', intro: 'Wander ramparts at golden hour, discover small galleries and settle into the rhythm of the southern coast.', best: 'History, design & beaches', time: '2 nights' },
  { name: 'Mirissa', type: 'Wild coast', image: '/images/mirissa-coast.png', intro: 'A laid-back ocean base for whale watching, reef swims, palm-fringed beaches and slow seafood lunches.', best: 'Ocean & relaxation', time: '2–4 nights' },
  { name: 'Yala', type: 'Wildlife country', image: '/images/destination-yala.png', intro: 'Trade city noise for open plains, lagoons and the possibility of meeting elephants, leopards and crocodiles.', best: 'Safaris & nature', time: '2 nights' },
  { name: 'Nuwara Eliya', type: 'Tea country', image: '/images/route-tea-tide.png', intro: 'Breathe in cool mountain air among rolling tea estates, colonial charm, gardens and quiet highland roads.', best: 'Tea, nature & cool air', time: '2 nights' },
  { name: 'Arugam Bay', type: 'East coast escape', image: '/images/adventure-kayaking-greenery.png', intro: 'Find long beach mornings, world-class surf, lagoons and an easygoing coastal rhythm on the island’s east.', best: 'Surf, lagoons & sunsets', time: '2–4 nights' },
]

export default function DestinationsPage() {
  return <PageFrame><PageHero eyebrow="Places to fall for" title={<>The island, <em>unfiltered.</em></>} intro="Choose the places that call to you. We will connect them into a thoughtful Sri Lankan journey around your interests, pace and budget." /><section className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><div className="max-w-2xl"><p className="eyebrow">A little local direction</p><h2 className="mt-3 font-serif text-5xl leading-none sm:text-6xl">Where will the island <em>take you?</em></h2><p className="mt-6 max-w-xl text-base leading-7 text-[#668079]">Every destination has its own mood. Browse the places our team knows deeply, then contact us for a route made around you — not a pre-set package.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{destinations.map((place) => <article key={place.name} className="group overflow-hidden rounded-[1.5rem] bg-white shadow-sm ring-1 ring-[#d8ddd4] transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="relative overflow-hidden"><img src={place.image} alt={`${place.name}, Sri Lanka`} className="h-64 w-full object-cover transition duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-[#173f3b]/85 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.16em] text-[#f3bf62]">{place.type}</span></div><div className="p-6"><h3 className="font-serif text-3xl text-[#173f3b]">{place.name}</h3><p className="mt-3 text-sm leading-6 text-[#668079]">{place.intro}</p><div className="mt-5 grid grid-cols-2 gap-3 border-y border-[#e4e9e2] py-4 text-xs text-[#668079]"><span className="flex items-center gap-2"><Sparkles size={14} className="text-[#d38b30]" />{place.best}</span><span className="flex items-center gap-2"><CalendarDays size={14} className="text-[#d38b30]" />{place.time}</span></div><Link href="/plan-trip" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#d38b30]">Build my route <ArrowRight size={15} /></Link></div></article>)}</div><div className="mt-20 rounded-[2rem] bg-[#173f3b] p-8 text-white sm:p-12"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><p className="eyebrow text-[#f3bf62]">Not sure where to start?</p><h2 className="mt-3 max-w-xl font-serif text-4xl">Tell us what kind of Sri Lanka you want to feel.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/70">Share your dates, interests and travel style. We will suggest the right destinations and shape a personal route for you.</p></div><Link href="/plan-trip" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-[#e7a94b] px-6 py-3.5 text-sm font-semibold text-[#173f3b]">Talk to our team <MapPin size={16} /></Link></div></div></section></PageFrame>
}
